# ============================================================================
# scan_deadcode.ps1 - Dead code scanner
#
# WHY THIS EXISTS
#   This project repeatedly hits the same class of bug: a method or constant
#   is written but NOTHING ever calls it, so the feature silently does nothing.
#   Already happened:
#     - BraveSword.attackProfile / advanceStage  (multi-hit weapon never worked)
#     - AngelSword.currentHits / advance         (same)
#     - ChallengeEffects.bulletHellCount         (rule 103 half-done)
#     - ChallengeEffects.peaceBrokenStatMult     (rule 152 stat bonus missing)
#     - ChallengeEffects.whaleUpgrade            (rule 160 had no UI entry)
#
# USAGE
#   cd E:\...\_EndShatteredBuild
#   .\tools\scan_deadcode.ps1
#   .\tools\scan_deadcode.ps1 -Filter "ChallengeEffects"
#
# OUTPUT
#   docs/DEADCODE_REPORT.md
# ============================================================================

param(
    [string]$Filter = ""
)

$ErrorActionPreference = "Stop"

$root    = Split-Path -Parent $PSScriptRoot
$javaDir = Join-Path $root "core\src\main\java"
$spdDir  = Join-Path $root "SPD-classes\src\main\java"
$outFile = Join-Path $root "docs\DEADCODE_REPORT.md"

Write-Host "Scanning:"
Write-Host "  $javaDir"
Write-Host "  $spdDir"

$files = @()
if (Test-Path $javaDir) { $files += Get-ChildItem $javaDir -Recurse -Filter *.java }
if (Test-Path $spdDir)  { $files += Get-ChildItem $spdDir  -Recurse -Filter *.java }
Write-Host "Source files: $($files.Count)"

# ---- read all sources (for the "is it referenced" search) ----
$all = @{}
foreach ($f in $files) {
    $all[$f.FullName] = Get-Content -LiteralPath $f.FullName -Raw -Encoding UTF8
}

# ---- extract public/protected method definitions ----
$defs = New-Object System.Collections.ArrayList

$methodRx = [regex]'(?m)^[ \t]*(public|protected)[ \t]+(static[ \t]+)?([\w\[\]<>,\.\? ]+?)[ \t]+(\w+)[ \t]*\(([^)]*)\)[ \t]*\{'

foreach ($f in $files) {
    if ($Filter -and ($f.Name -notmatch $Filter)) { continue }
    $src = $all[$f.FullName]
    $rel = $f.FullName.Replace("$root\", "")

    foreach ($m in $methodRx.Matches($src)) {
        $name = $m.Groups[4].Value
        $args = $m.Groups[5].Value

        if ($name -in @("main","toString","equals","hashCode","clone","getClass")) { continue }
        if ($name -match '^(if|for|while|switch|catch|return|new)$') { continue }

        # skip overrides: they are driven by the parent class
        $start = [Math]::Max(0, $m.Index - 400)
        $before = $src.Substring($start, $m.Index - $start)
        $isOverride = $before -match '@Override[ \t\r\n]*$'

        $line = ($src.Substring(0, $m.Index) -split "`n").Count

        [void]$defs.Add([pscustomobject]@{
            File     = $rel
            Class    = $f.BaseName
            Name     = $name
            Vis      = $m.Groups[1].Value
            Static   = ($m.Groups[2].Value.Trim() -ne "")
            Args     = $args.Trim()
            Override = $isOverride
            Line     = $line
        })
    }
}

Write-Host "Method definitions: $($defs.Count)"

# ---- count references ----
$results = New-Object System.Collections.ArrayList
foreach ($d in $defs) {
    $esc  = [regex]::Escape($d.Name)
    $callRx = [regex]("\b$esc\s*\(")
    $count = 0
    $callers = New-Object System.Collections.ArrayList

    foreach ($kv in $all.GetEnumerator()) {
        $n = $callRx.Matches($kv.Value).Count
        if ($n -gt 0) {
            $count += $n
            [void]$callers.Add(($kv.Key.Replace("$root\", "")))
        }
    }

    [void]$results.Add([pscustomobject]@{
        File      = $d.File
        Class     = $d.Class
        Name      = $d.Name
        Args      = $d.Args
        Override  = $d.Override
        Line      = $d.Line
        RefCount  = $count
        NumCallers = $callers.Count
    })
}

$dead     = @($results | Where-Object { $_.RefCount -le 1 -and -not $_.Override })
$onlySelf = @($results | Where-Object { $_.RefCount -gt 1 -and $_.NumCallers -eq 1 -and -not $_.Override })
$okCount  = @($results | Where-Object { $_.Override -or ($_.RefCount -gt 1 -and $_.NumCallers -gt 1) }).Count

Write-Host ""
Write-Host "=== RESULT ==="
Write-Host "  Never referenced:        $($dead.Count)"
Write-Host "  Self-file only:          $($onlySelf.Count)"
Write-Host "  OK (cross-file/override):$okCount"

# ---- report ----
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# Dead Code Report")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("Auto-generated by ``tools/scan_deadcode.ps1``.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("Scanned **$($files.Count)** source files, **$($defs.Count)** public/protected method definitions.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Why this scan exists")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("This project repeatedly hits one class of bug: **a method is written but")
[void]$sb.AppendLine("nothing ever calls it**, so the feature silently does nothing.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Already happened | Symptom |")
[void]$sb.AppendLine("|---|---|")
[void]$sb.AppendLine("| ``BraveSword.attackProfile`` / ``advanceStage`` | multi-hit weapon never worked |")
[void]$sb.AppendLine("| ``AngelSword.currentHits`` / ``advance`` | same |")
[void]$sb.AppendLine("| ``ChallengeEffects.bulletHellCount`` | rule 103 half-done |")
[void]$sb.AppendLine("| ``ChallengeEffects.peaceBrokenStatMult`` | rule 152 stat bonus missing |")
[void]$sb.AppendLine("| ``ChallengeEffects.whaleUpgrade`` | rule 160 had no UI entry |")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("---")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Never referenced ($($dead.Count))")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("**Most suspicious.** Defined but never called anywhere.")
[void]$sb.AppendLine("")

if ($dead.Count -eq 0) {
    [void]$sb.AppendLine("(none)")
} else {
    [void]$sb.AppendLine("| File | Method | Line |")
    [void]$sb.AppendLine("|---|---|---|")
    foreach ($d in ($dead | Sort-Object File, Line)) {
        [void]$sb.AppendLine("| ``$($d.File)`` | ``$($d.Name)($($d.Args))`` | $($d.Line) |")
    }
}

[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Referenced only inside its own file ($($onlySelf.Count))")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("**Second most suspicious.** Only used locally - either it should be")
[void]$sb.AppendLine("private, or an internal feature was never exposed.")
[void]$sb.AppendLine("")

if ($onlySelf.Count -eq 0) {
    [void]$sb.AppendLine("(none)")
} else {
    [void]$sb.AppendLine("| File | Method | Line |")
    [void]$sb.AppendLine("|---|---|---|")
    foreach ($d in ($onlySelf | Sort-Object File, Line)) {
        [void]$sb.AppendLine("| ``$($d.File)`` | ``$($d.Name)($($d.Args))`` | $($d.Line) |")
    }
}

[void]$sb.AppendLine("")
[void]$sb.AppendLine("---")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Notes")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("- Overridden methods (with ``@Override``) are excluded - the parent drives them.")
[void]$sb.AppendLine("- ``private`` methods are not scanned (too many false positives).")
[void]$sb.AppendLine("- References are matched by ``name(`` - same-name methods may false-positive.")
[void]$sb.AppendLine("- Generated: " + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))

$docsDir = Split-Path -Parent $outFile
if (-not (Test-Path $docsDir)) { New-Item -ItemType Directory -Path $docsDir -Force | Out-Null }
[System.IO.File]::WriteAllText($outFile, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))

Write-Host ""
Write-Host "Report: $outFile"
Write-Host ""
Write-Host "=== Never referenced (first 40) ==="
$dead | Sort-Object File, Line | Select-Object -First 40 | ForEach-Object {
    Write-Host ("  {0,-20} {1,-44} L{2}" -f $_.Class, "$($_.Name)($($_.Args))", $_.Line)
}
